// Custom Cloudflare Worker entry.
//
// Wraps the OpenNext-generated fetch handler (which serves the Next.js app) and adds
// a `scheduled()` handler for the Cron Trigger configured in wrangler.jsonc. The cron
// is the fallback processor for the job/email queue — the happy path sends inline from
// the submit server action.
//
// The scheduled handler dispatches an internal request to the existing
// `/api/cron/process-jobs` route (guarded by CRON_SECRET) through the OpenNext handler,
// so all job-processing logic stays in the Next bundle and this entry needs no app
// imports (which keeps Wrangler's esbuild from having to resolve the `@/` alias).
//
// `./.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so it does
// not exist until after a build. This file is excluded from the project's tsconfig and
// bundled by Wrangler at deploy time.
//
// @ts-nocheck
import openNextHandler from './.open-next/worker.js';

export default {
  fetch: openNextHandler.fetch,

  async scheduled(_event, env, ctx) {
    const base = env.NEXT_PUBLIC_SITE_URL || 'https://supplai.rlago.com';
    const request = new Request(new URL('/api/cron/process-jobs', base), {
      method: 'GET',
      headers: { Authorization: `Bearer ${env.CRON_SECRET ?? ''}` },
    });

    ctx.waitUntil(
      openNextHandler
        .fetch(request, env, ctx)
        .then(res => console.log('[Cron] process-jobs status:', res.status))
        .catch(err => console.error('[Cron] process-jobs failed:', err))
    );
  },
};
